#!/sbin/sh
# TWRP A/B Installer Backend
# by osm0sis, Dees_Troy and topjohnwu
# Adapted by Giovix92 for SHRP

OUTFD=/proc/self/fd/$2;
ZIPFILE="$3";

ui_print() { $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> $OUTFD; }
abort() { ui_print "$1"; exit 1; }

# detect Magisk Manager/booted flashing
ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false;
$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;

ui_print "----------------------------------------";
ui_print "-                                       ";
ui_print "- SHRP installer for A/B devices        ";
ui_print "- Device: $device                       ";
ui_print "- Version: 2.3.2 Stable                 ";
ui_print "-                                       ";
ui_print "----------------------------------------";
ui_print " ";

# /dev/tmp is safe for both booted and recovery installs
tmp=/dev/tmp/shrp-install;
# target partition without the slot suffix
target=/dev/block/bootdevice/by-name/boot;

ui_print "[i] Unpacking the installer...";
ui_print " ";
rm -rf $tmp;
mkdir -p $tmp;
unzip -o "$ZIPFILE" -d $tmp || abort "[!!] Failed to extract zip! Check recovery logs.";

ui_print "[i] Copying SHRP add-ons...";
rm -rf /sdcard/SHRP/
mkdir -p /sdcard/SHRP/
cp -r $tmp/Files/SHRP/addons /sdcard/SHRP

cd $tmp;
cp $tmp/Files/SHRP/addons/magiskboot $tmp;
tool=$tmp/magiskboot;
test "$tool" || abort "[!!] No magiskboot binary found! Aborting.";
recoverycpio=`(ls ramdisk-twrp.cpio || ls ramdisk-recovery.cpio) 2>/dev/null`;
test "$recoverycpio" || abort "[!!] No SHRP ramdisk cpio found! Aborting.";

chmod 755 $tool;

workDIR=$tmp/work/;
mkdir -p $workDIR;
cd $workDIR;

for slot in a b; do
  ui_print "[i] Making a backup of boot_$slot...";
  dd if=/dev/block/bootdevice/by-name/boot_$slot of=/sdcard/boot_$slot.img;
  ui_print "[i] Running boot image patcher on slot $slot...";
  dd if=/dev/block/bootdevice/by-name/boot_$slot of=recovery.img;

  $tool unpack -h recovery.img;

  # kernel string want_initramfs -> skip_initramfs (Magisk)
  $tool hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
  # kernel string trip_initramfs -> skip_initramfs (SuperSU)
  $tool hexpatch kernel 747269705F696E697472616D6673 736B69705F696E697472616D6673;

  # boot.img header cmdline remove skip_override (flar2 patch)
  sed -i "s|$(grep '^cmdline=' header | cut -d= -f2-)|$(grep '^cmdline=' header | cut -d= -f2- | sed -e 's/skip_override//' -e 's/  */ /g' -e 's/[ \t]*$//')|" header;

  cp -f $tmp/$recoverycpio $workDIR;
  cp -f $recoverycpio ramdisk.cpio;
  $tool repack recovery.img newRec.img;

  dd if=newRec.img of=/dev/block/bootdevice/by-name/boot_$slot || abort "[!!] Unable to find patched bootimg! Aborting.";
  rm -r *;

  ui_print "[i] Slot $slot patched!";
done;
ui_print "[i] Cleaning up...";
cd /;
rm -rf /dev/tmp;
ui_print "[i] Boot image patching complete!";
ui_print "[i] Note: you're now unrooted.!";


